### ISSUE TITLE
Restore on second click

### ISSUE THREAD

**Issue by hockeymikey** [Zren/plasma-applet-win7showdesktop#15]
Just like in Windows 7, have an option that allows for all windows to be minimized and then restored in the same location when clicked a second time.

**Comment by Zren** [comment]
That's what the "Show Desktop" setting does. It will also restore if you open a file on the desktop or hide.

My "Minimize All" setting doesn't have that feature though, mostly because I was lazy and didn't copy this code from the default widget:

https://github.com/KDE/plasma-desktop/blob/master/applets/minimizeall/package/contents/ui/main.qml#L51

You can quickly test your changes by running `kquitapp5 plasmashell; kstart5 plasmashell` to restart the Plasma desktop+panel.

**Comment by hockeymikey** [comment]
@Zren So for whatever reason isMinimized always returns false. The default one doesn't work either. Got any ideas why?
