### ISSUE TITLE
"Move cursor" icon stays visible

### ISSUE THREAD

**Issue by marhkb** [Zren/plasma-applet-win7showdesktop#7]
I use latte dock, but there is an icon that won't go away as shown in the screenshot.
The "Win7 Show Desktop" is the most right applet beside the clock.

![grafik](https://user-images.githubusercontent.com/3630213/67616843-a3d52a00-f7dd-11e9-9fec-4c6de8081f0a.png)

**Comment by Zren** [comment]
Ah, I guess latte is always unlocked. I do know how to detect latte so I'll fix it.

* Add `property bool isInLatter: false` to `main.qml`.
* https://github.com/KDE/latte-dock/commit/c14470c7426645267909dc5e85322c75a92a38da
* https://github.com/KDE/latte-dock/commit/1f51524d428e4dea0bb0443d87074e49c5b43703#diff-7c6d6fefd9b2f74d2c5a76f56ad23395R39-R41
* Then use `!isInLatte && plasmoid.immutability == PlasmaCore.Types.Mutable`

The issue is, how do I make the widget wider when in in Latte's "Dock Settings" panel editor mode.

**Comment by Zren** [comment]
What version of Latte do you have? `latte-dock --version`

https://repology.org/project/latte-dock/versions

* I notice Kubuntu 18.04 still has `0.7.4`, which I don't think I can detect.
* I think Latte v8 has `isInLatte`, but v9 doesn't.
* Latte v9 has a new `latteBridge` with `latteBridge.inEditMode`. I've tested this works in Manjaro which has v0.9.3.

**Comment by marhkb** [comment]
0.9.3 from Arch Linux

**Comment by Zren** [comment]
Sorry, looks like I never released the widget after testing the release in latte-dock. I just released v9, which should fix this (for you). I've reuploaded v7 of the widget for anyone still on Ubuntu 18.04 which only has latte-dock v0.7.
